baseurl = "https://bobstrecansky.com"
title = "Bob Strecansky"
languageCode = "en-us"
theme = "hello-friend-ng"

googleAnalytics = "140001660"
pluralizeListTitles = false

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "Bob Strecansky's Blog"
  keywords = "homepage, blog"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "tech"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[permalinks]
  tech = "/tech/:year/:month/:day/:title/"    
  food = "/food/:year/:month/:day/:title/"
  musings = "/musings/:year/:month/:day/:title/"

[languages]
  [languages.en]
    title = "Staff Engineer @Mailchimp"
    homeSubtitle = "Experience with Web Performance, Reliability, and Security"
    keywords = "Performance"
    copyright = "2021"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Bob Strecansky"
      logoHomeLink = "https://bobstrecansky.com/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  [[menu.main]]
    identifier = "food"
    name       = "🍲 food"
    url        = "https://bobstrecansky.com/food/"

  [[menu.main]]
    identifier = "tech"
    name       = "👨‍💻 tech"
    url        = "https:///bobstrecansky.com/tech/"

  [[menu.main]]
    identifier = "works"
    name       = "👷 works"
    url        = "https://bobstrecansky.com/works/"

  [[menu.main]]
    identifier = "musings"
    name       = "😎 musings"
    url        = "https://bobstrecansky.com/musings/"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/bobstrecansky"


  [[params.social]]
    name = "github"
    url  = "https://github.com/bobstrecansky"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/bobstrecansky"

  staticDir = ["static"]
